@ECHO OFF
REM
REM Sample script used to distribute obfuscated python scripts with py2exe
REM
REM Before run it, all TODO variables need to set correctly.
REM

SETLOCAL

REM TODO: zip tool used to replace files in compressed .zip file
SET ZIP=zip.exe

REM TODO: Absolute path for python installed, python.exe should be here
SET PYPATH=C:\Users\User\AppData\Local\Programs\Python\Python36-32

REM TODO: Absolute path in which all python scripts will be obfuscated
SET SOURCE=D:\My Workspace\Project\Src

REM TODO: Entry script filename, must be relative to %SOURCE%
SET ENTRY_SCRIPT=main.py

REM TODO: Output path of py2exe
REM       An executable binary file and library.zip generated by py2exe should be here
SET OUTPUT=D:\My Workspace\Project\Dist

REM TODO: output path for saving project config file, and obfuscated scripts
SET PROJECT=D:\My Workspace\Project\Pyarmor-Dist

REM Check output of py2exe
IF NOT EXIST "%OUTPUT%\library.zip" (
  ECHO
  ECHO No output of py2exe found in path %OUTPUT%
  ECHO
  ECHO Run py2exe, for example
  ECHO
  ECHO   python setup.py py2exe
  ECHO
  GOTO END
)

REM Check Python
SET PYTHON=%PYPATH%\python.exe
IF NOT EXIST "%PYTHON%" (
  ECHO
  ECHO No python.exe found in %PYPATH%
  ECHO
  GOTO END
)

REM Check Pyarmor
SET PYARMOR_PATH=%PYPATH%\Lib\site-packages\pyarmor
IF NOT EXIST "%PYARMOR_PATH%\pyarmor.py" (
  ECHO
  ECHO No pyarmor installed, run "pip install pyarmor" to install it first
  ECHO If pyarmor has been installed other than pip, set variable PYARMOR_PATH to the right path
  ECHO 
  GOTO END
)

REM Create a project
CD /D %PYARMOR_PATH%
%PYTHON% pyarmor.py init --type=app --src=%SOURCE% --entry=%ENTRY_SCRIPT% %PROJECT%

REM Change to project path, there is a convenient script pyarmor.bat
cd /D %PROJECT%

REM This is the key, change default runtime path, otherwise dynamic library _pytransform could not be found
.\pyarmor.bat config --runtime-path="" --disable-restrict-mode=1 --manifest "include queens.py, exclude setup.py"

REM Obfuscate scripts without runtime files, only obfuscated scripts are generated
.\pyarmor.bat build --no-runtime

IF ERRORLEVEL 1 GOTO END

REM Copy pytransform.py and obfuscated entry script to source
COPY %PYARMOR_PATH%\pytransform.py %SOURCE%
COPY %SOURCE%\%ENTRY_SCRIPT% %ENTRY_SCRIPT%.bak
COPY dist\%ENTRY_SCRIPT% %SOURCE%

SETLOCAL
  CD /D %SOURCE%
  %PYTHON% setup.py py2exe
  IF ERRORLEVEL 1 (
    ECHO Failed to run py2exe
    GOTO END
  )
ENDLOCAL

REM Restore modified entry script
MOVE %ENTRY_SCRIPT%.bak %SOURCE%\%ENTRY_SCRIPT%

REM Compile obfuscated script .py to .pyc
$PYTHON -m compileall dist

REM Replace the original python scripts with obfuscated scripts in zip file
SETLOCAL
  CD dist
  %ZIP% -r %OUTPUT%\library.zip *.pyc
  IF ERRORLEVEL 1 GOTO END
ENDLOCAL  

REM Generate runtime files only
.\pyarmor.bat build --only-runtime --output %PROJECT%\runtime-files

IF ERRORLEVEL 1 GOTO END

REM Copy runtime files to output path of py2exe
COPY %PROJECT%\runtime-files\* %OUTPUT%

ECHO
ECHO All the python scripts have been obfuscated in the output path %OUTPUT% successfully.
ECHO

:END

ENDLOCAL
PAUSE
